### ISSUE TITLE
Change MediaCie wiki pages to MedIA

### ISSUE THREAD

**Issue by kasteelharry** [Inter-Actief/Beheer_Issues#77]
Last year the MedIA changed its name to MedIA and they would like to have their wiki pages to use this name as well. Besides updating the name of the pages we might also have to chage all the links to the pages. I do not know how many there are.

**Comment by jeffreybakker** [comment]
This was also discussed last year, when, after the merge of the FlitCie and Cinema, the MediaCie decided it wanted to be the MedIA. The conclusion was to keep the AD name `MediaCie` instead of `Media` as it would require another large refactoring in all systems. Additionally, the term `media` is already taken in our systems for actual media, instead of an committee, see [media.ia.utwente.nl](https://media.ia.utwente.nl).

Therefore, while MedIA might be the public name of the committee, it shall remain MediaCie for all WWW and SysCom purposes.
