### ISSUE TITLE
Wiki search results number off

### ISSUE THREAD

**Issue by MiniLars** [Inter-Actief/Beheer_Issues#95]
When searching for something on the (new) wiki, the search result number and the actual number of results is off. For example, when the results number is 25, two pages may be filled (sometimes only even 1), and the third page (which is still accessible) returns "No pages match your query.".

See picture for when searching "mail". The result number is 70. The first 4 pages are filled with 10 results each, the 5th page has 5 results and page 6 and 7 return the above error.

Page 5:
![Screenshot_20231115-194753_Brave.jpg](https://github.com/Inter-Actief/Beheer_Issues/assets/66956762/1bedfee2-8d4a-482b-887a-e5016e8834f0)

Page 6:
![Screenshot_20231115-194801_Brave.jpg](https://github.com/Inter-Actief/Beheer_Issues/assets/66956762/52eabd1a-9ed3-485c-8d08-279b5900437b)

**Comment by kasteelharry** [comment]
Hi Lars, thanks for letting us know about this. From our testing, we noticed this is due to pages that are outside your permission scope being counted in the search results. However, they are then hidden in the attached screenshots. If there is no existing issue describing this then we highly recommend you open one. You can find existing issues [here](https://github.com/requarks/wiki/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). 

We do kindly request you to **not** include any screenshot or reference of our wiki in the issue at requarks/wikijs out of precaution.
